agent: transformer_agent
device: "cuda:0"
train:
  train_feature_list_file: data/MVAD/train_list_50
  train_corpus_file: data/MVAD/corpus_M-VAD_train.txt
  train_batch_size: 32
val:
  val_feature_list_file: data/MVAD/val_list_50
  val_corpus_file: data/MVAD/corpus_M-VAD_test.txt
  val_batch_size: 32
  val_interval: 1
test:
  test_feature_list_file: data/MVAD/test_list_50
  test_corpus_file: data/MVAD/corpus_M-VAD_test.txt
  test_batch_size: 32
graph:
  model:
    encoder_d_model: 512
    decoder_d_model: 512
    num_heads: 8
    encoder_num_layers: 2
    decoder_num_layers: 4
    dff: 2048
    dropout: 0.1
  optimizer:
    learning_rate: 0.0001
    beta1: 0.98
    beta2: 0.998

    



{
  "cut_sequence": true,
  "tokenizer_file": "data/MVAD/tokenizer.model",
  "load_checkpoint": null,
  "save_checkpoint": "checkpoint/transformer",
  "summary_writer_dir": "logs/transformer",
  "tar_vocab_size": 5000,
  "inp_max_sequence_size": 50,
  "tar_max_sequence_size": 50,
  "max_seq_length": 80,
  "pad_id": 0,
  "start_id": 1,
  "end_id": 2,
  "beam_k": 5,
  "beam_min_length": 3,
  "beam_num_required": 25,
  "epoch": 70,
}
